### ISSUE TITLE
Convert UTC time shown in Azure?

### ISSUE THREAD

**Issue by chaoscreater** [QOAL/localisetime#14]
When looking at certain resource graphs in Azure, the time shown is in UTC instead of local time and it doesn't seem like there's a way to change this. I've looked around for userscripts and extensions to try to change the time to local time and I came across your extension, which looks promising. Unfortunately, it didn't change the time shown in Azure.

Below is a link to some sample code I copied from Chrome's DevTools: 
https://pastebin.com/Gef8GAfD

![image](https://user-images.githubusercontent.com/18227319/141647108-72ec6c3d-1d8e-4409-821a-d6aadf42c007.png)

![image](https://user-images.githubusercontent.com/18227319/141703469-7437ff5a-0714-4550-bd80-cc78f9639031.png)

![image](https://user-images.githubusercontent.com/18227319/141703308-612bf78d-44fe-4a5d-a97a-5534147d4133.png)

I think perhaps the issue in the screenshot above is that you only see the keyword "UTC" when you hover your mouse on top of the graph. On the X-axis of the graph, it only shows the time without any timezone, but the time shown on the graph is always going to be UTC. Is there a way to just force detection of time and hardcode to assume it is UTC, then convert it to local time? Maybe you can add an option to specify certain webpages that will always convert to local time, based on UTC.

You can create a free account in Azure and get $200 of free credit for a trial. You can then create a free Azure App Service and then go into -> Diagnose & Solve Problems -> Troubleshoot and you should be able to find a graph that shows only in UTC time.

![image](https://user-images.githubusercontent.com/18227319/141647185-34aa5317-3a49-416a-8bbd-6164da626838.png)

![image](https://user-images.githubusercontent.com/18227319/141647177-086a11bd-b16c-4276-b7cb-a094ff7932b3.png)

I would very much appreciate it if you could make this work. I'm not a programmer and I don't have the brains to make something like this. I'm willing to donate to you if you can make this work.

**Comment by QOAL** [comment]
For the time being does using the pop-up window's manual conversion feature work for you?

![image](https://user-images.githubusercontent.com/217349/141650079-5ea809cb-353c-4774-9292-d7394c9da6c0.png)
Since they're already in UTC, just can just click `OK`.

If that does work for you then I think I could make a domain whitelist feature, that'll automatically localise times based on a chosen time zone, on page on load and mutation.
It does sound like a handy feature!

**Comment by chaoscreater** [comment]
> 
> 
> For the time being does using the pop-up window's manual conversion feature work for you?
> 
> ![image](https://user-images.githubusercontent.com/217349/141650079-5ea809cb-353c-4774-9292-d7394c9da6c0.png) Since they're already in UTC, just can just click `OK`.
> 
> If that does work for you then I think I could make a domain whitelist feature, that'll automatically localise times based on a chosen time zone, on page on load and mutation. It does sound like a handy feature!

Thanks for your reply! I've tried that already and it doesn't work unfortunately.

I'm not exactly sure how your code works and I'm not a programmer myself. I think your code might be scanning for specific timezone strings/keywords and if found, then convert them to local time? In that case, that might be the reason why it's not working for me on that particular Azure page. If you take a look at the code in the Pastebin link I shared, you'll find that there's actually no reference to the timezone. All it shows is just the date and the time. The screenshot shows "UTC" on the X-axis, but it doesn't show UTC in the actual date/time in the code itself.

**Comment by QOAL** [comment]
1.26.0 is rolling out now. Once that is available to you, please can you try manually converting again.

I found that the times were being localised, however the layout code was invalid in an SVG, which is what powers those graphs.

**Comment by chaoscreater** [comment]
Thanks for the update. I've just tried it on both Firefox and Chrome and I made sure the extension version is up to date. Unfortunately, neither have worked, I don't see any changes.......since you have re-opened this issue, I'm guessing you're probably still working on it.

To make things a bit more complicated, I've noticed that the time shown in Azure graphs are not very consistent. Some graphs show just the date & time, whereas some show the timezone. The time is still shown in UTC, just that when you hover your mouse over the graph, sometimes the result displayed is different, depending on which graph you're looking at. I've updated the original post to better explain this, please take a look at the difference between the 2nd and 3rd screenshot.

Furthermore, not all Azure graphs are shown in UTC. Some graphs support showing data in local time. So I think there probably needs to be a filter to only target the change on specific URLs. But if this is getting too complex, I can just toggle the addon on/off.

Lastly, for manually converting times, is it possible for us to set the default timezone? I'm almost always going to be using my timezone and so it'll be a lot easier to just set that as the default, instead of manually finding and choosing my timezone from the dropdown menu.

**Comment by chaoscreater** [comment]
@QOAL Sorry, just checking that you've got my previous message? I'm not able to see any changes with the new 1.26 version.

**Comment by QOAL** [comment]
I did, I'm sorry for not responding. I've not been feeling to great all week.

It's disappointing that 1.26.0 didn't help at all. I got that to work nicely with the markup example of yours.
![image](https://user-images.githubusercontent.com/217349/142657928-db832262-ca6f-4151-964b-53537deb7372.png)

From the top of my head, and without actually looking at Azure yet, the only other things stopping nice localisation are:
* The SVGs being displayed inside iframes. This would be a pain in the ass.
* The times are only shown when you hover over the graph, or something, so they're not visible when manually localising.
For the last point, I think it would be actually handy to, when the extension detects something in the page changes, search for times missing a timezone (if a manual one has been given) along side its normal detection.

Manually converted times are always converted to your local time. The time that you pick from the drop down is the source time zone used by the page. (So if the page uses UTC and you're in ET, you'd pick UTC)
Making it remember the last selected timezone might be nice, but not too handy across domains.

**Comment by chaoscreater** [comment]
Sorry to hear that, hope you're feeling better now.

I'm not sure I understand your first point about iframes (I'm not really a web dev or programmer sorry). But for your 2nd point, yes the times only show when I hover over the graph.

**Comment by chaoscreater** [comment]
@QOAL Sorry to re-open this, but I've just tested the latest version and it still doesn't work unfortunately.......

If you create an App Service (free) in Azure, then go to Diagnose & Solve problems -> Troubleshoot and then just click on either of the top 2 options and you'll see the graph:

![image](https://user-images.githubusercontent.com/18227319/143131724-ba0c1cf3-4844-48d2-bdc9-baa51922ac61.png)


![image](https://user-images.githubusercontent.com/18227319/143131586-916b2e98-dbfb-43f2-9159-90f210a1106d.png)

**Comment by QOAL** [comment]
I don't really want to mess around signing up for this just to figure it out.
However I did some digging, found this page ( https://docs.microsoft.com/en-us/azure/data-explorer/time-series-analysis ) and ran the filter query.
I'm assuming that they use the same library (Which is highcharts) across the board. 

I've had mix luck in my brief testing.
The queries on the page above don't seem to localise well (I think I've seen the time disappear)
But the times on this demo page work well: https://www.highcharts.com/demo/combo-meteogram#https://api.met.no/weatherapi/locationforecast/2.0/compact?lat=51.50853&lon=-0.12574&altitude=25

I've also reverted the changes from 1.26.1 for Firefox.
It works fine locally with no changes compared to the released version, which was exhibiting odd behaviour. No idea why. Chrome seems fine too.

If you could go in to the Inspector and find a reference to Highcharts then things will start moving in the right direction again:
![image](https://user-images.githubusercontent.com/217349/143143754-f56e3c85-e52b-4b7b-8aa4-195711dd21fe.png)

I'm sorry that this turned out to be a pain for both of us.

**Comment by chaoscreater** [comment]
Thanks for your reply. To clarify, there are different types of Azure graphs and some graphs show local time, some only show UTC time. Some graphs use different methods of displaying the results and I don't think the one I'm looking at is using highcharts.

I think it might be best for you to take a look at the exact graph I'm looking at. I've created a test account for you, so you don't have to worry about signing up to Azure. I can't figure out a way to DM you directly in GitHub, so I'll just share the crednetials in a one-time password link. The link will expire upon view, so make sure you note down the credentials. Once you're done with the testing, please let me know and I will remove the account.

1. Browse to portal.azure.com and use the username + password in the link below:
https://1ty.me/TgqsD

2. Choose this option to skip MFA setup (you don't need it):

![image](https://user-images.githubusercontent.com/18227319/143146968-8a3d940d-3983-40da-8e32-b3463377d3a5.png)

3. Browse to the following link:
https://portal.azure.com/#@fd70ff72-6987-45ec-b726-2cd24095e116/resource/subscriptions/59abf72e-604f-444c-9c24-ecddd1ed6e10/resourceGroups/appservice/providers/Microsoft.Web/sites/rickytestappservice1/troubleshoot

Choose one of the options at the bottom and click Troubleshoot:

![image](https://user-images.githubusercontent.com/18227319/143147049-dd960166-0d80-438c-bcf1-1ea07ceb00ba.png)

**Comment by QOAL** [comment]
I appreciate you doing this. It's helped me pin point the exact issue.

I'll just publicly explain my findings:

The graphs are contained in an iframe, like I suspected.
An iframe is a way of embedding a different web page into the current page.
This means that when the extension goes to look for times, it never sees the graph, as it's in a separate page.

Turns out there's a setting I can enable that allows an extension to run in iframes!
I flipped it, and manual conversion works.
So I feel like an idiot, but as a stop gap, you should be good to go.
1.26.5 is rolling out now, once you have it please confirm, and you can nuke the azure stuff above in peace.
(And tell me if you hate the emoji clocks next to all of the times in graphs)

Also the graphs are created using the highcharts library, so I can look for them specifically, and check the x-axis title for "Time (X)" then use X on times without abbreviations.
Please let me know if the time in the graphs tooltip doesn't get localised. I wasn't able to find it in the page markup just now, so I'm hoping I can just find it in a demo chart elsewhere if there's an issue.

I can also look for the `Time Range` selector element, and extract the abbreviation from that. That would need to be an azure specific hack, which might be fine.

**Comment by chaoscreater** [comment]
@QOAL Awesome, it works now! Thanks for your persistence in getting this working, I really appreciate it.

I did notice a small bug though, which is that the Y-Axis values got modified into a local time, even though they aren't actually a time value:

![image](https://user-images.githubusercontent.com/18227319/143668030-7526ec71-77ba-4478-9332-350c9ec6a183.png)

![image](https://user-images.githubusercontent.com/18227319/143668011-afe375e0-7088-413b-b026-db81e185a6c3.png)

Other than that, I think it's awesome!

**Comment by QOAL** [comment]
The y-axis issue is a very tricky one.
4.15 PST looks a bit like a time, just like 0.25 looks a bit like a time too, if you add a time zone abbreviation. (0.25 CET)
So even though that looks ridiculous, I'm not going to fix that.

I have spent a good long while today looking at the tooltip issue.
It's really strange, and I can't fully fix it.

I found some graphs use additional elements for the text, which was an easy fix.

Then I found a nice demo that exhibited what I assume is the same behaviour as the graphs on Azure.
And I cannot fix it. It don't think I'm at fault, but it is very odd.

Here's the demo: https://www.highcharts.com/demo/dynamic-update
Here's what it looks like:
![image](https://user-images.githubusercontent.com/217349/143697428-3b9c1b45-10da-40db-a9f3-db3ccd510493.png)
And here's the markup:
![image](https://user-images.githubusercontent.com/217349/143697890-51e4c663-9cc5-411f-a4a9-66c815f4b31b.png)

When you move over the graph the extension gets a list of changed elements like normal, but they're not of the right elements.
![image](https://user-images.githubusercontent.com/217349/143701986-fdb9de21-85da-4809-aa34-cc5579cf24da.png)
You get the title of the tooltip, and then one or two seemingly blank text nodes.
It turns out they're not blank. They have a [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space) in them.
And those "blank" nodes are the `tspan`s with the `class="highcharts-br"`.
It feels like, and this behaviour is exactly the same in Firefox and Chrome, that the browser is giving me the "blank" node prior to the text that was changed.

It gets weirder because I made a local copy of the graph, and if it has ordinary white space, or nothing, instead of the zero-width space it works.
![image](https://user-images.githubusercontent.com/217349/143707689-448219ef-93bf-4009-a4c0-e12503b20239.png)

I hope that helps you understand my investigation, and why I am unable to fix it on my end.

So there's still potentially domain/library specific handling of the graphs, so they automatically localise.
And/or having a per domain/page time zone preset.

**Comment by chaoscreater** [comment]
Thanks man, I appreciate you looking into this.

I just came across this extension (there's Chrome and Firefox) made by someone else and his one is able to convert the times in the graph!

https://chrome.google.com/webstore/detail/opjfchgghhechkchondagenjpobfjooe

![image](https://user-images.githubusercontent.com/18227319/143787157-f49fd702-5c26-441c-bf72-259d6a43cd6e.png)

I think you can use something like this to view the source code:
https://robwu.nl/crxviewer/

**Comment by QOAL** [comment]
![image](https://user-images.githubusercontent.com/217349/143890140-31ff7a73-a619-41a4-a13f-a515c31f1c1d.png)

We're done now I think.

The issue was one step further back in the code.

I've also added an (on by default) setting that tries to avoid matching non-integer numbers when manually converting times.

**Comment by chaoscreater** [comment]
That's awesome man! It works!

Sorry just one last request if that's alright. Can you make the extension toggle-able, so that if I don't want it to convert the time, I can just toggle it OFF? At the moment, the way I use it is I go to a specific page in Azure, I'll do a manual time conversion using the extension, then I'll need to refresh the webpage so clear the converted times. 

Sometimes, the refreshed webpage doesn't take me to where I want it to be, because when you drill down into specific graphs or sections in Azure, it doesn't actually update the URL.....so refreshing the webpage is not really a good way to clear all the converted times.

**Comment by QOAL** [comment]
Well those are out of scope of this issue but lets clarify what you're after.

1) Ability to clear the current manually selected time zone to localise from.
   This should be pretty trivial.

2) Ability to pause the extension, so it doesn't localise any times.
   This should also be trivial, I might need to play with the UI a bit though.

**Comment by chaoscreater** [comment]
Yup, that's correct. The extension automatically converts all times shown on a webpage and I only need this to happen when I want choose to do so. Once the times on a webpage are converted, I would like to clear it to reset it back to normal.

**Comment by QOAL** [comment]
1.28.X has basic support for these things. 
You should be able to pause the extension, it's global rather than per page though.
You can now clear a manually selected time zone, stopping the extension from continuing to look for times to localise with it.

I haven't made it so previously converted times are reverted back to plain text though.
It's reasonable enough to do with most times, but the ones that get the emoji clocks next to them are more of a pain to find and revert. Something for the future.

**Comment by chaoscreater** [comment]
That's awesome, thank you!
