### ISSUE TITLE
Strange behavior on text selection with some websites

### ISSUE THREAD

**Issue by Naheulf** [QOAL/localisetime#18]
On some site there something odd with text selection when the extension is active.

For example takes the [AlekAundra answer]( https://www.scribblehub.com/read/501431-player--you-have-died-reset-in-progress/chapter/511459/?cid=1374802) from Jun 15, 2022.

The second sentence is "Next chapter will be up Saturday 3PM PST / 6PM EST." if the extension is enabled the two times are converted to <kbd>🕐 01:00</kbd> (except the clock is an svg instead of the unicode char)

If you select it with the mouse nothing special occur.

Now click at least one time on the first time and select the text again. It's now converted to the static text `Next chapter will be up Saturday 🕐01:00 / 01:00.`

Trying to narrow down the requirement for this behaviour I first found out that the extension MUST be UN-paused to this happen.

However playing more with (un)pause the extension, click to (un)convert the time and (un)select the text I found something event strange : the extension fool/prank me:
- some times i can select the displayed text (except the clock) while the extension is active, even after convert the time.
- on time, with the extension active, I was able to select the text two times in a row without something occur. However the text was converted with the third conversion... 🙃

Note : I use Firefox x64 101.0.1 on Windows 10.

**Comment by QOAL** [comment]
This behaviour is caused by a script on that website.
`setItem`, in https://www.scribblehub.com/wp-content/themes/writeit-child/js/jsmenu-hl.js?ver=1.0.2
It just loves mangling the text by adding \ufeff ([character info](https://www.fileformat.info/info/unicode/char/feff/index.htm)) where you're selecting.
![image](https://user-images.githubusercontent.com/217349/174136498-cd7ee623-09ca-46a1-92ba-eb5e118e17c3.png)

So this might be the extension unexpectedly having handling the mangled time, followed by the website changing the DOM.

(I'm busy with another project at the minute, but this seems like a fun thing to try and mitigate.)

**Comment by QOAL** [comment]
Sorry for the delay in fixing this.
I've found the issue and have pushed [2802755](https://github.com/QOAL/localisetime/commit/28027550edb9ef79360fda248ecfbb994461185c).
1.28.13 is rolling out now.
Please let me know if this update has any unexpected side effects.

Thank you for taking the time to report this, I appreciate it!

**Comment by QOAL** [comment]
I've reverted this fix for now. I noticed it causing page slow downs once or twice. I'll come up with a better fix soon.

**Comment by Naheulf** [comment]
Okay.
